services:
  app:
    image: ghcr.io/bignellrp/my-app3:latest
    container_name: my-app3
    networks:
      - br1
    ports:
      - "2379:8000" # This must be updated before deployment
    restart: always
    environment:
      - TZ=Europe/London

networks:
  br1:
    external: true
    name: br1