services:
  app:
    image: ghcr.io/bignellrp/${{ github.event.repository.name }}:latest
    container_name: ${{ github.event.repository.name }}
    networks:
      - br1
    ports:
      - "xxxx:8000" # This must be updated before deployment
    restart: always
    environment:
      - TZ=Europe/London

networks:
  br1:
    external: true
    name: br1